# Dev profile: local PostgreSQL, fully driven by environment variables
spring.config.activate.on-profile=dev

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-cool-cloud-a1swkdc9-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_W7MCpAtmO5YS&sslmode=require&channelBinding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_W7MCpAtmO5YS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# Optional: Enable H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
