spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server configuration
server.port=${PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always

# Logging configuration
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:kmharimng@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fyfa xhwy bqha spsr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false

app.admin.email=admin@site.com
app.admin.username=admin
app.admin.password=Admin@123